## 1st stage

FROM eclipse-temurin:11.0.16.1_1-jdk-jammy AS build

COPY . /src
WORKDIR /src
RUN set -eux; \
    ./gradlew bootJar; \
    java -Djarmode=layertools -jar build/libs/*.jar extract --destination /dist

## 2nd stage

FROM gcr.io/distroless/java17-debian11:nonroot

EXPOSE 8080
WORKDIR /app

COPY --from=build /dist/dependencies/ .
COPY --from=build /dist/spring-boot-loader/ .
COPY --from=build /dist/snapshot-dependencies/ .
COPY --from=build /dist/application/ .

ENTRYPOINT [ "java" ]
CMD [ "org.springframework.boot.loader.JarLauncher" ]
