spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres?ssl=false"
    username: postgres
    password: mysecretpassword
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 30000
      idleTimeout: 60000
      maxLifetime: 1800000
      jdbc4ConnectionTest: true
      minimumIdle: 0
      maximumPoolSize: 10

  mvc:
    logResolvedException: false

management:
  endpoints:
    enabledByDefault: false
    web:
      basePath: /management
  endpoint:
    health:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: behind-proxy

server:
  tomcat:
    remoteip:
      remote-ip-header: "x-forwarded-for"
      protocol-header: "x-forwarded-proto"
